import Head from 'next/head';
import Navbar from '../components/navbar';

export default function Home() {
  return (
    <div className={"bg-[#282828] text-white h-screen"}>
      <Head>
        <title>My Resume Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar></Navbar>
      </header>
      <main>
      </main>

      <footer>
      </footer>
    </div>
  )
}
